name: version_comparator
description: An app version comparator between app stores and local version. It support Android, iOS and Huawei platforms. 
  Also custom version compare is possible.
repository: https://github.com/E-MRE/version_comparator/
issue_tracker: https://github.com/E-MRE/version_comparator/issues?q=is%3Aopen 
version: 1.0.23

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Json Operations
  json_annotation: ^4.9.0

  #Networking
  http: ^1.3.0

  #Package & Device Info
  package_info_plus: ^8.2.0
  device_info_plus: ^11.2.2

  #Launch URL
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  #Json Operation
  json_serializable: ^6.8.0

flutter:
