name: version_comparator
description: An app version comparator between app stores and local version. It support Android, iOS and Huawei platforms. 
  Also custom version compare is possible.
repository: https://github.com/E-MRE/version_comparator/
issue_tracker: https://github.com/E-MRE/version_comparator/issues?q=is%3Aopen 
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Json Operations
  json_annotation:

  #Query operations
  collection:

  #Networking
  http: ^0.13.5

  #Package & Device Info
  package_info_plus:
  device_info_plus:

  #Launch URL
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.2.1
  #Json Operation
  json_serializable:

flutter:
