name: version_comparator
description: An app version comparator between app stores and local version. It support Android, iOS and Huawei platforms. 
  Also custom version compare is possible.
repository: https://github.com/E-MRE/version_comparator/
issue_tracker: https://github.com/E-MRE/version_comparator/issues?q=is%3Aopen 
version: 1.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Json Operations
  json_annotation: ^4.8.1

  #Query operations
  collection: ^1.17.1

  #Networking
  http: ^1.0.0

  #Package & Device Info
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2

  #Launch URL
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.2.1
  #Json Operation
  json_serializable: ^6.6.1

flutter:
